import { MaterialCommunityIcons } from "@expo/vector-icons";

export type SportIconName = keyof typeof MaterialCommunityIcons.glyphMap;

export const SPORT_ICONS: Record<string, SportIconName> = {
  running: "run",
  padel: "tennis",
  gym: "dumbbell",
  football: "soccer",
  basketball: "basketball",
  tennis: "tennis-ball",
  swimming: "swim",
  volleyball: "volleyball",
  cycling: "bike",
  hockey: "hockey-sticks",
  rugby: "rugby",
  boxing: "boxing-glove",
  martial_arts: "karate",
  athletics: "medal",
  crossfit: "weight-lifter",
  climbing: "hiking",
  skateboarding: "skateboarding",
  handball: "handball",
  table_tennis: "table-tennis",
  badminton: "badminton",
  rowing: "rowing",
  kayak: "kayak",
  wrestling: "wrestling",
  judo: "karate",
  taekwondo: "karate",
  fencing: "fencing",
  archery: "archery",
  weightlifting: "weight-lifter",
  gymnastics: "gymnastics",
  triathlon: "triathlon",
  equestrian: "horse",
  simulator_f1: "racing-helmet",
  simulator_flight: "airplane",
  simulator_rally: "car-sports",
  simulator_golf: "golf",
  simulator_vr: "virtual-reality",
  simulator_shooting: "target",
  other: "map-marker",
};
