export type SportType =
  | "running"
  | "padel"
  | "gym"
  | "football"
  | "basketball"
  | "tennis"
  | "swimming"
  | "volleyball"
  | "cycling"
  | "hockey"
  | "rugby"
  | "boxing"
  | "martial_arts"
  | "athletics"
  | "crossfit"
  | "climbing"
  | "skateboarding"
  | "handball"
  | "table_tennis"
  | "badminton"
  | "rowing"
  | "kayak"
  | "wrestling"
  | "judo"
  | "taekwondo"
  | "fencing"
  | "archery"
  | "weightlifting"
  | "gymnastics"
  | "triathlon"
  | "equestrian"
  | "simulator_f1"
  | "simulator_flight"
  | "simulator_rally"
  | "simulator_golf"
  | "simulator_vr"
  | "simulator_shooting"
  | "other";

export type Place = {
  id: string;
  name: string;
  latitude: number;
  longitude: number;
  type: SportType;
  description?: string;
  rating?: number;
  address?: string;
  schedule?: string;
  price?: string;
  phone?: string;
};
